on:
  push:
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          git config --global user.name "John Doe"
          git config --global user.email "jdoe@email.com"
          git config --global core.autocrlf false
          git config --global core.filemode false

      - name: fetch angle
        run: |
          $env:Path += ';' + $pwd + '/depot_tools'
          $env:DEPOT_TOOLS_WIN_TOOLCHAIN = 0

          mkdir angle
          cd angle
          fetch --no-history angle
