on:
  push:
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git --depth 1
          git config --global user.name "John Doe"
          git config --global user.email "jdoe@email.com"
          git config --global core.autocrlf false
          git config --global core.filemode false

      - name: fetch angle
        run: |
          $env:Path += ';' + $pwd + '/depot_tools'
          $env:DEPOT_TOOLS_WIN_TOOLCHAIN = 0

          mkdir angle
          cd angle
          fetch --no-history angle
          gn gen out/Release --args='is_component_build=false target_cpu=x86 is_debug=false angle_enable_d3d9=true angle_enable_d3d11=false angle_enable_gl=false angle_enable_metal=false angle_enable_null=false angle_enable_vulkan=false angle_enable_essl=true angle_enable_glsl=true'
          autoninja -C out/Release
